# Generated by Django 6.0.3 on 2026-04-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlightspa', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='site',
            field=models.CharField(default='vipspa', max_length=20),
        ),
    ]
