# Generated by Django 6.0.3 on 2026-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlightspa', '0003_gallery_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='site',
            field=models.CharField(default='redlightspa', max_length=20),
        ),
    ]
