# Generated by Django 6.0.3 on 2026-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlightspa', '0010_service_meta_description_service_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
