# Generated by Django 6.0.3 on 2026-03-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VIP Spa Dhaka', max_length=100)),
                ('logo', models.ImageField(upload_to='site_assets/')),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_subtitle', models.TextField(blank=True)),
                ('banner_image', models.ImageField(upload_to='banners/')),
                ('about_title', models.CharField(default='About Our Spa', max_length=200)),
                ('about_description', models.TextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
