# Generated by Django 6.0.3 on 2026-03-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0002_homepage_siteconfig_delete_websiteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='homepage/about/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='homepage/about/')),
                ('feature_1', models.CharField(blank=True, max_length=100)),
                ('feature_1_icon', models.ImageField(blank=True, null=True, upload_to='homepage/about/features/')),
                ('feature_2', models.CharField(blank=True, max_length=100)),
                ('feature_2_icon', models.ImageField(blank=True, null=True, upload_to='homepage/about/features/')),
                ('feature_3', models.CharField(blank=True, max_length=100)),
                ('feature_3_icon', models.ImageField(blank=True, null=True, upload_to='homepage/about/features/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('contact_label', models.CharField(blank=True, max_length=100)),
                ('contact_value', models.CharField(blank=True, max_length=100)),
                ('video_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/blogs/')),
                ('details_link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Blog Section',
                'verbose_name_plural': 'Blog Section',
            },
        ),
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/brands/')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/gallery/')),
                ('view_link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke_text', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('shape_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InstagramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/instagram/')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InstagramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Instagram Section',
                'verbose_name_plural': 'Instagram Section',
            },
        ),
        migrations.CreateModel(
            name='MarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_1', models.CharField(blank=True, max_length=255)),
                ('session_2', models.CharField(blank=True, max_length=255)),
                ('session_3', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Pricing Section',
                'verbose_name_plural': 'Pricing Section',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='homepage/services/items/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/services/items/')),
                ('details_link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='homepage/services/')),
            ],
            options={
                'verbose_name': 'Service Section',
                'verbose_name_plural': 'Service Section',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='homepage/team/')),
                ('details_link', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='homepage/testimonials/')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/video/')),
            ],
            options={
                'verbose_name': 'Video Section',
                'verbose_name_plural': 'Video Section',
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
