# Generated by Django 6.0.3 on 2026-03-31 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0003_aboutsection_blogpost_blogsection_brandlogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('general', 'General Service (Section 1)'), ('top', 'Top Service (Section 3)')], default='general', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_image', models.FileField(blank=True, help_text='SVG preferred', null=True, upload_to='services/icons/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='services/main/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vipspa.servicecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
