# Generated by Django 6.0.3 on 2026-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0004_servicecategory_serviceitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='logo',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_description',
            field=models.TextField(default='Default description...'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logos/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='mon_fri_time',
            field=models.CharField(default='09:00-20:00', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sat_sun_time',
            field=models.CharField(default='09:00-18:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(default='Address here'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(default='mail@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone_number',
            field=models.CharField(default='012-3456-789', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='VIP SPA', max_length=100),
        ),
    ]
