# Generated by Django 6.0.3 on 2026-04-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0005_alter_siteconfig_options_remove_siteconfig_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='sat_sun_time',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sat_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sun_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='mon_fri_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
