# Generated by Django 6.0.3 on 2026-04-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0008_category_alter_blogpage_tags_blogcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
