# Generated by Django 6.0.3 on 2026-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0009_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='site',
            field=models.CharField(choices=[('vipspa', 'VIP Spa'), ('redlightspa', 'Red Light Spa')], default='vipspa', max_length=20),
        ),
    ]
