# Generated by Django 6.0.3 on 2026-04-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0010_gallery_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='site',
            field=models.CharField(default='vipspa', max_length=20),
        ),
    ]
