# Generated by Django 6.0.3 on 2026-04-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0011_alter_gallery_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_sections/')),
                ('button_text', models.CharField(blank=True, default='', max_length=50)),
                ('button_url', models.URLField(blank=True, default='', max_length=500)),
                ('extra_field', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
