# Generated by Django 6.0.3 on 2026-04-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0012_homesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', '-id']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='details_link',
        ),
        migrations.AddField(
            model_name='service',
            name='faq_data',
            field=models.JSONField(blank=True, default=list, help_text="[{'q': '...', 'a': '...'}] ফরম্যাটে"),
        ),
        migrations.AddField(
            model_name='service',
            name='long_description',
            field=models.TextField(blank=True, help_text='ডিটেইলস পেইজে দেখানোর জন্য'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='সার্ভিস লিস্টে দেখানোর জন্য'),
        ),
        migrations.AlterField(
            model_name='service',
            name='background_image',
            field=models.ImageField(default='', upload_to='homepage/services/items/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(default='', upload_to='homepage/services/items/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
