# Generated by Django 6.0.3 on 2026-04-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0014_dynamicpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicpage',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/banners/'),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='content',
            field=models.TextField(help_text='Write your page content here (HTML supported)'),
        ),
    ]
