# Generated by Django 6.0.3 on 2026-04-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0015_alter_dynamicpage_options_dynamicpage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpage',
            name='bottom_content',
            field=models.TextField(blank=True, help_text='Extra text to show after the image', null=True),
        ),
    ]
