# Generated by Django 6.0.3 on 2026-04-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0014_alter_aboutsection_id_alter_blogcomment_id_and_more'),
        ('vipspa', '0016_dynamicpage_bottom_content'),
    ]

    operations = [
    ]
