# Generated by Django 6.0.3 on 2026-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0018_alter_aboutsection_id_alter_blogcomment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='call_number',
            field=models.CharField(blank=True, help_text='Direct call number for buttons', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description for search engines', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO focus title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social share preview image', null=True, upload_to='site/seo/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='og_title',
            field=models.CharField(blank=True, help_text='Facebook/Social share title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_url',
            field=models.URLField(blank=True, default='https://vipspadhaka.com'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Full telegram link (e.g., https://t.me/username)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20, null=True),
        ),
    ]
