# Generated by Django 6.0 on 2026-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0019_remove_siteconfig_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='faq_data',
        ),
        migrations.RemoveField(
            model_name='service',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_overview',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_description',
        ),
        migrations.AddField(
            model_name='service',
            name='details_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/services/items/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/services/items/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
