# Generated by Django 6.0.3 on 2026-05-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0020_alter_service_options_remove_service_faq_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='address',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='call_number',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='email',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='mon_fri_time',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='sat_time',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='sun_time',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telegram_link',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='About Description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='About Title'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='blog_meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Blog Description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='blog_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blog Title'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Title'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Home Description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Home Title'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pricing_meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Pricing Description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pricing_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pricing Title'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='services_meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Services Page Description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='services_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Services Page Title'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Common social share image', null=True, upload_to='site/seo/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_url',
            field=models.URLField(blank=True, default='https://elitespagulshan.com'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
