# Generated by Django 6.0.3 on 2026-05-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0021_remove_siteconfig_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
