# Generated by Django 6.0.3 on 2026-05-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0023_alter_service_options_remove_service_details_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
