# Generated by Django 6.0.3 on 2026-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipspa', '0024_siteconfig_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='ব্লগ পোস্টের একটি ছোট সারসংক্ষেপ যা গুগল সার্চে দেখাবে', null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='গুগল সার্চ রেজাল্টের জন্য টাইটেল (ফাঁকা রাখলে মেইন টাইটেলটিই ব্যবহৃত হবে)', max_length=255, null=True),
        ),
    ]
